### ISSUE TITLE
list 텍스트 변환 문제

### ISSUE THREAD

**Issue by ghost** [Non-duality/Schedule-Management#1]
qt5에서 메시지 창을 띄울때 사용하는 qstring 과 텔레그램 메시지 전송에 필요한 string 간의
변환 함수 필요

**Comment by Non-duality** [comment]
메세지 박스 내용(QString)을 가져오기 보다는
전역변수 sort_task_list를 변환해서 사용하면 될듯
ex) 
`time = list(sort_task_list[0].keys())[0]`
`task = list(sort_task_list[0].values())[0]`
time, task 모두 string 형식으로 저장되는 것을 확인
