### ISSUE TITLE
가끔 시간이 안맞을때가 있음

### ISSUE THREAD

**Issue by ghost** [Non-duality/Schedule-Management#2]

**Comment by Non-duality** [comment]
시간이 안맞다는 것은 알림이 안울린다는 소리?
알림이 가끔 안울리는 이유는 TimeThread객체의 쓰레드가 30초 주기이기 때문인 것으로 판단됨.
이 30초를 10초나 5초로 줄이면 알림이 안울리는 오류를 없앨 수 있음

`stime.sleep(30)` → `stime.sleep(5)`
