### ISSUE TITLE
년,월,일 데이터 추가로 인한 데이터 형식 변환

### ISSUE THREAD

**Issue by Non-duality** [Non-duality/Schedule-Management#3]
현재 이러한 형식으로 ( List 안에 Dictionary )
`[{"am:hours:minutes" : "할일"}]`
데이터를 저장하고 있는데

달력을 추가함으로서 년,월,일,요일에 대한 데이터를 더 추가해야하는 문제가 생김
좋은 방법 있으면 알려주길 바람

**Comment by ghost** [comment]
2중 딕셔너리 방식으로 
[{"년:월:일:요일" : {"am:시간:분" : "할일"}]
식으로 저장하면 될듯함.
